INSERT INTO "permissions" ("id", "code", "created_at")
SELECT gen_random_uuid(), code, CURRENT_TIMESTAMP
FROM unnest(ARRAY[
  'LIBRARY_BOOK_READ', 'LIBRARY_BOOK_CREATE', 'LIBRARY_BOOK_UPDATE', 'LIBRARY_BOOK_DELETE',
  'LIBRARY_COPY_READ', 'LIBRARY_COPY_CREATE', 'LIBRARY_COPY_UPDATE',
  'LIBRARY_LOAN_READ', 'LIBRARY_LOAN_CREATE', 'LIBRARY_LOAN_RETURN', 'LIBRARY_LOAN_RENEW',
  'LIBRARY_HISTORY_READ',
  'LIBRARY_RESERVATION_READ', 'LIBRARY_RESERVATION_CREATE', 'LIBRARY_RESERVATION_CANCEL',
  'LIBRARY_FINE_READ', 'LIBRARY_FINE_PAY', 'LIBRARY_FINE_ADJUST',
  'LIBRARY_SETTINGS_READ', 'LIBRARY_SETTINGS_UPDATE', 'LIBRARY_DASHBOARD_READ'
]) AS code
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "roles" ("id", "name", "created_at", "updated_at")
VALUES (gen_random_uuid(), 'LIBRARY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r."id", p."id" FROM "roles" r CROSS JOIN "permissions" p
WHERE r."name" IN ('LIBRARY', 'SUPER_ADMIN') AND p."code" LIKE 'LIBRARY\_%'
ON CONFLICT DO NOTHING;
