import type { Permission } from './types';
export const AUDIT_PERMISSIONS: Permission[] = [
  'AUDIT_READ',
  'OPERATION_SCOPE_ALL',
  'FOLLOWUP_READ',
  'SMALL_GROUP_READ',
  'MINISTRY_READ',
  'SCHEDULE_READ',
  'ATTENDANCE_READ',
  'NOTIFICATION_READ',
  'MEMBER_READ',
  'USER_READ',
  'FINANCE_CONTRIBUTION_READ',
  'FINANCE_INVOICE_READ',
  'LIBRARY_HISTORY_READ',
  'VISITOR_READ',
  'EVENT_READ',
];
