export const STATUS_LABELS: Record<string, string> = {
  UPLOADED: 'Enviado',
  PROCESSING: 'Processando',
  READY_FOR_REVIEW: 'Pronto para revisão',
  CONFIRMED: 'Confirmado',
  FAILED: 'Falhou',
  ACTIVE: 'Ativo',
  INACTIVE: 'Inativo',
  INVITED: 'Convidado',
  DISABLED: 'Desativado',
  PENDING: 'Pendente',
  COMPLETED: 'Concluído',
  CANCELLED: 'Cancelado',
  AVAILABLE: 'Disponível',
  LOANED: 'Emprestado',
  RETURNED: 'Devolvido',
  EXPIRED: 'Expirado',
  RESERVED: 'Reservado',
  OVERDUE: 'Em atraso',
  LOST: 'Perdido',
  MAINTENANCE: 'Manutenção',
  DISPOSED: 'Retirado',
  OPEN: 'Em aberto',
  PAID: 'Pago',
  FORGIVEN: 'Perdoado',
  WAITING: 'Em espera',
  READY: 'Pronto',
  FULFILLED: 'Atendido',
  NEW: 'Novo',
  CONTACTED: 'Contactado',
  ARCHIVED: 'Arquivado',
  SCHEDULED: 'Agendado',
  CLASSIFIED: 'Classificado',
  RECONCILED: 'Cadastrado',
  PENDING_REVIEW: 'Revisão pendente',
  POSSIBLE_DUPLICATE: 'Possível duplicidade',
  REJECTED: 'Ignorado',
  INCOME: 'Receita',
  EXPENSE: 'Despesa',
  TITHE: 'Dízimo',
  OFFERING: 'Oferta',
  DONATION: 'Doação',
  OTHER: 'Outro',
};

// Operational vocabulary shares the same badges throughout the application.
import { operationLabels } from '../pages/operations/operation-config';
Object.assign(STATUS_LABELS, operationLabels);
